/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'leosi' at '07/08/16 18:47' with Gradle 2.14
 *
 * @author leosi, @date 07/08/16 18:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	System.out.println( "lose 5 ".replaceAll("lose|best", "").trim() );
	}
}
